//go:build !ignore_autogenerated

/*
Auto-generated DeepCopy methods
*/

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *USBConnection) DeepCopyInto(out *USBConnection) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new USBConnection.
func (in *USBConnection) DeepCopy() *USBConnection {
	if in == nil {
		return nil
	}
	out := new(USBConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *USBConnection) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *USBConnectionList) DeepCopyInto(out *USBConnectionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]USBConnection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new USBConnectionList.
func (in *USBConnectionList) DeepCopy() *USBConnectionList {
	if in == nil {
		return nil
	}
	out := new(USBConnectionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *USBConnectionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *USBConnectionSpec) DeepCopyInto(out *USBConnectionSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new USBConnectionSpec.
func (in *USBConnectionSpec) DeepCopy() *USBConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(USBConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *USBConnectionStatus) DeepCopyInto(out *USBConnectionStatus) {
	*out = *in
	if in.ConnectedAt != nil {
		in, out := &in.ConnectedAt, &out.ConnectedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new USBConnectionStatus.
func (in *USBConnectionStatus) DeepCopy() *USBConnectionStatus {
	if in == nil {
		return nil
	}
	out := new(USBConnectionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *USBDevice) DeepCopyInto(out *USBDevice) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new USBDevice.
func (in *USBDevice) DeepCopy() *USBDevice {
	if in == nil {
		return nil
	}
	out := new(USBDevice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *USBDevice) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *USBDeviceList) DeepCopyInto(out *USBDeviceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]USBDevice, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new USBDeviceList.
func (in *USBDeviceList) DeepCopy() *USBDeviceList {
	if in == nil {
		return nil
	}
	out := new(USBDeviceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *USBDeviceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *USBDeviceSpec) DeepCopyInto(out *USBDeviceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new USBDeviceSpec.
func (in *USBDeviceSpec) DeepCopy() *USBDeviceSpec {
	if in == nil {
		return nil
	}
	out := new(USBDeviceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *USBDeviceStatus) DeepCopyInto(out *USBDeviceStatus) {
	*out = *in
	in.LastSeen.DeepCopyInto(&out.LastSeen)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new USBDeviceStatus.
func (in *USBDeviceStatus) DeepCopy() *USBDeviceStatus {
	if in == nil {
		return nil
	}
	out := new(USBDeviceStatus)
	in.DeepCopyInto(out)
	return out
}
